version: "2"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CREATE_TOPICS=search_index:1:1:compact
      # - KAFKA_BROKER_ID=10
      # - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
    restart: always
    depends_on:
      - zookeeper