name: Continous Integration
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install poetry poethepoet
          poe init
      - name: Ensure Formatted
        run: |
          poetry run black --check backend tests
      - name: Setup local MongoDB
        uses: supercharge/mongodb-github-actions@1.8.0
      - name: Ensure documentation
        run: |
          poetry run pydocstyle
      - name: Test with pytest
        run: |
          poetry run pytest
